name: Preencher Formulário

on:
  schedule:
    - cron: '55 10 * * THU'  # Executa às 10:55 UTC
  workflow_dispatch:

jobs:
  fill-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências do Python
        run: |
          pip install selenium webdriver-manager

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Instalar ChromeDriver (versão correta)
        run: |
          # Instalação do Google Chrome
          sudo apt update
          sudo apt install -y google-chrome-stable

          # Verifica a versão do Chrome instalada
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          echo "Versão do Chrome instalada: $CHROME_VERSION"

          # Obtém a versão correta do ChromeDriver
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")

          # Verifica se a variável foi corretamente preenchida
          if [[ -z "$DRIVER_VERSION" ]]; then
            echo "Erro: Não foi possível encontrar a versão correta do ChromeDriver."
            exit 1
          fi

          echo "Versão do ChromeDriver encontrada: $DRIVER_VERSION"

          # Baixa e instala o ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip
          unzip -o chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Confirma se o ChromeDriver foi instalado corretamente
          chromedriver --version


      - name: Executar script de automação
        env:
          DISPLAY: ':99.0'
        run: python form_automation.py
