name: Preencher Formulário

on:
  schedule:
    - cron: '55 10 * * THU'  # Executa às 10:55 UTC
  workflow_dispatch:

jobs:
  fill-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências do Python
        run: |
          pip install selenium webdriver-manager

      - name: Instalar Chrome e ChromeDriver
        run: |
          # Atualiza os pacotes e instala o Google Chrome
          sudo apt update
          sudo apt install -y google-chrome-stable

          # Obtém a versão exata do Chrome instalada
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f1)
          echo "Versão do Chrome instalada: $CHROME_VERSION"

          # Obtém a versão mais recente do ChromeDriver para essa versão do Chrome
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR" || echo "")

          # Se a versão do ChromeDriver não for encontrada, tenta usar a última versão disponível
          if [[ -z "$DRIVER_VERSION" || "$DRIVER_VERSION" == *"Error"* ]]; then
            echo "Erro ao encontrar versão específica para Chrome $CHROME_MAJOR. Usando versão mais recente do ChromeDriver."
            DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          echo "Versão do ChromeDriver encontrada: $DRIVER_VERSION"

          # Baixa e instala o ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip
          unzip -o chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Confirma se o ChromeDriver foi instalado corretamente
          chromedriver --version

      - name: Executar script de automação
        env:
          DISPLAY: ':99.0'
        run: python form_automation.py
