name: Preencher Formulário

on:
  schedule:
    - cron: '55 10 * * THU'  # Executa às 10:55 UTC (ajuste conforme necessário)
  workflow_dispatch:  # Permite disparar manualmente

jobs:
  fill-form:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências do Python
        run: |
          pip install selenium webdriver-manager

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Instalar ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          wget -q "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Executar script de automação
        env:
          DISPLAY: ':99.0'  # Evita problemas com interface gráfica
        run: python form_automation.py
